language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
install:
  - npm install
  - bower install
  - gem install sass
  - gem install compass
before_script: gulp
script: karma start karma.config.js --single-run
