language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
  - npm install -g tsd
install:
  - npm install
  - bower install
  - tsd install
  - gem install sass
  - gem install compass
before_script: gulp
script: npm run-script test
